-- Table: public.goals
-- Description: Individual goal records for matches

CREATE TABLE public.goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    match_id BIGINT NOT NULL,
    player_id BIGINT NOT NULL,
    kicker_id BIGINT NOT NULL,
    goal_type TEXT NOT NULL,
    amount SMALLINT NOT NULL,
    team SMALLINT NOT NULL,
    "scoreTeam1" BIGINT NULL,
    "scoreTeam2" BIGINT NULL,
    gamemode TEXT NOT NULL DEFAULT ''::text,
    
    CONSTRAINT goals_pkey PRIMARY KEY (id),
    CONSTRAINT goals_kicker_id_fkey FOREIGN KEY (kicker_id) REFERENCES kicker (id),
    CONSTRAINT goals_match_id_fkey FOREIGN KEY (match_id) REFERENCES matches (id),
    CONSTRAINT goals_player_id_fkey FOREIGN KEY (player_id) REFERENCES player (id)
) TABLESPACE pg_default;

-- Indexes
-- goals_pkey: CREATE UNIQUE INDEX goals_pkey ON public.goals USING btree (id)

-- RLS Policies
-- See: ../policies/goals_policies.sql
