-- Table: public.kicker
-- Description: Kicker/Foosball table definitions

CREATE TABLE public.kicker (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    name TEXT NOT NULL,
    access_token UUID NOT NULL DEFAULT gen_random_uuid(),
    avatar TEXT NULL,
    season_config JSONB NOT NULL DEFAULT '{"frequency": "quarterly", "season_mode": false}'::jsonb,
    admin UUID NULL,
    
    CONSTRAINT kicker_pkey PRIMARY KEY (id),
    CONSTRAINT kicker_admin_fkey FOREIGN KEY (admin) REFERENCES auth.users (id)
) TABLESPACE pg_default;

-- Indexes
-- kicker_pkey: CREATE UNIQUE INDEX kicker_pkey ON public.kicker USING btree (id)

-- RLS Policies
-- (none currently)
