-- Table: public.matches
-- Description: Match records with scores, MMR changes, and player assignments

CREATE TABLE public.matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    end_time TIMESTAMP WITH TIME ZONE NULL,
    player1 BIGINT NOT NULL,
    player2 BIGINT NOT NULL,
    player3 BIGINT NULL,
    player4 BIGINT NULL,
    status TEXT NOT NULL DEFAULT 'active'::text,
    "scoreTeam1" SMALLINT NOT NULL DEFAULT '0'::smallint,
    "scoreTeam2" SMALLINT NOT NULL DEFAULT '0'::smallint,
    "mmrChangeTeam1" BIGINT NULL,
    "mmrChangeTeam2" BIGINT NULL,
    "mmrPlayer1" BIGINT NULL,
    "mmrPlayer2" BIGINT NULL,
    "mmrPlayer3" BIGINT NULL,
    "mmrPlayer4" BIGINT NULL,
    gamemode TEXT NOT NULL DEFAULT '1on1'::text,
    start_time TIMESTAMP WITH TIME ZONE NULL,
    kicker_id BIGINT NOT NULL,
    nr BIGINT NULL,
    season_id BIGINT NULL,
    
    CONSTRAINT matches_pkey PRIMARY KEY (id),
    CONSTRAINT matches_kicker_id_fkey FOREIGN KEY (kicker_id) REFERENCES kicker (id),
    CONSTRAINT matches_player1_fkey FOREIGN KEY (player1) REFERENCES player (id),
    CONSTRAINT matches_player2_fkey FOREIGN KEY (player2) REFERENCES player (id),
    CONSTRAINT matches_player3_fkey FOREIGN KEY (player3) REFERENCES player (id),
    CONSTRAINT matches_player4_fkey FOREIGN KEY (player4) REFERENCES player (id)
) TABLESPACE pg_default;

-- Indexes
-- matches_pkey: CREATE UNIQUE INDEX matches_pkey ON public.matches USING btree (id)

-- Triggers
-- See: ../triggers/before_match_insert.sql

-- RLS Policies
-- See: ../policies/matches_policies.sql
