-- Table: public.player_history
-- Description: Daily snapshots of player statistics for historical tracking

CREATE TABLE public.player_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    player_name TEXT NOT NULL,
    player_id BIGINT NOT NULL,
    user_id UUID NOT NULL,
    kicker_id BIGINT NOT NULL,
    mmr BIGINT NOT NULL,
    mmr2on2 BIGINT NOT NULL,
    wins BIGINT NOT NULL,
    losses BIGINT NOT NULL,
    wins2on2 BIGINT NOT NULL,
    losses2on2 BIGINT NOT NULL,
    wins2on1 BIGINT NOT NULL,
    losses2on1 BIGINT NOT NULL,
    duration BIGINT NOT NULL DEFAULT '0'::bigint,
    duration2on2 BIGINT NOT NULL DEFAULT '0'::bigint,
    duration2on1 BIGINT NOT NULL DEFAULT '0'::bigint,
    
    CONSTRAINT player_history_pkey PRIMARY KEY (id),
    CONSTRAINT player_history_kicker_id_fkey FOREIGN KEY (kicker_id) REFERENCES kicker (id),
    CONSTRAINT player_history_player_id_fkey FOREIGN KEY (player_id) REFERENCES player (id),
    CONSTRAINT player_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id)
) TABLESPACE pg_default;

-- Indexes
-- player_history_pkey: CREATE UNIQUE INDEX player_history_pkey ON public.player_history USING btree (id)

-- RLS Policies
-- (none currently)
