-- Table: public.player
-- Description: Player profiles linked to auth users

CREATE TABLE public.player (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    name TEXT NOT NULL DEFAULT '""'::text,
    wins BIGINT NOT NULL DEFAULT '0'::bigint,
    losses BIGINT NOT NULL DEFAULT '0'::bigint,
    mmr BIGINT NOT NULL DEFAULT '1000'::bigint,
    avatar TEXT NULL,
    user_id UUID NOT NULL,
    mmr2on2 BIGINT NOT NULL DEFAULT '1000'::bigint,
    wins2on2 BIGINT NOT NULL DEFAULT '0'::bigint,
    losses2on2 BIGINT NOT NULL DEFAULT '0'::bigint,
    kicker_id BIGINT NOT NULL,
    
    CONSTRAINT player_pkey PRIMARY KEY (id),
    CONSTRAINT player_kicker_id_fkey FOREIGN KEY (kicker_id) REFERENCES kicker (id),
    CONSTRAINT player_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id)
) TABLESPACE pg_default;

-- Indexes
-- player_pkey: CREATE UNIQUE INDEX player_pkey ON public.player USING btree (id)

-- RLS Policies
-- See: ../policies/player_policies.sql
