-- Migration: Create match_comments, match_reactions, and comment_reactions tables (kopecht schema)
-- For comments, likes, and emoji reactions on matches

SET search_path TO kopecht;

-- 1. Create match_comments table
CREATE TABLE IF NOT EXISTS kopecht.match_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    edited_at TIMESTAMPTZ,
    match_id BIGINT NOT NULL REFERENCES kopecht.matches(id) ON DELETE CASCADE,
    player_id BIGINT NOT NULL REFERENCES kopecht.player(id) ON DELETE CASCADE,
    kicker_id BIGINT NOT NULL REFERENCES kopecht.kicker(id) ON DELETE CASCADE,
    content VARCHAR(1000) NOT NULL
);

-- Create indexes for match_comments
CREATE INDEX IF NOT EXISTS idx_match_comments_match_id ON kopecht.match_comments(match_id);
CREATE INDEX IF NOT EXISTS idx_match_comments_player_id ON kopecht.match_comments(player_id);
CREATE INDEX IF NOT EXISTS idx_match_comments_kicker_id ON kopecht.match_comments(kicker_id);
CREATE INDEX IF NOT EXISTS idx_match_comments_created_at ON kopecht.match_comments(created_at);

-- 2. Create match_reactions table (reactions on matches)
CREATE TABLE IF NOT EXISTS kopecht.match_reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    match_id BIGINT NOT NULL REFERENCES kopecht.matches(id) ON DELETE CASCADE,
    player_id BIGINT NOT NULL REFERENCES kopecht.player(id) ON DELETE CASCADE,
    kicker_id BIGINT NOT NULL REFERENCES kopecht.kicker(id) ON DELETE CASCADE,
    reaction_type TEXT NOT NULL,
    UNIQUE(match_id, player_id, reaction_type)
);

-- Create indexes for match_reactions
CREATE INDEX IF NOT EXISTS idx_match_reactions_match_id ON kopecht.match_reactions(match_id);
CREATE INDEX IF NOT EXISTS idx_match_reactions_player_id ON kopecht.match_reactions(player_id);

-- 3. Create comment_reactions table (reactions on comments)
CREATE TABLE IF NOT EXISTS kopecht.comment_reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    comment_id BIGINT NOT NULL REFERENCES kopecht.match_comments(id) ON DELETE CASCADE,
    player_id BIGINT NOT NULL REFERENCES kopecht.player(id) ON DELETE CASCADE,
    kicker_id BIGINT NOT NULL REFERENCES kopecht.kicker(id) ON DELETE CASCADE,
    reaction_type TEXT NOT NULL,
    UNIQUE(comment_id, player_id, reaction_type)
);

-- Create indexes for comment_reactions
CREATE INDEX IF NOT EXISTS idx_comment_reactions_comment_id ON kopecht.comment_reactions(comment_id);
CREATE INDEX IF NOT EXISTS idx_comment_reactions_player_id ON kopecht.comment_reactions(player_id);

-- 4. Enable Row Level Security
ALTER TABLE kopecht.match_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE kopecht.match_reactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE kopecht.comment_reactions ENABLE ROW LEVEL SECURITY;

-- 5. RLS Policies for match_comments

-- Users can view comments for matches in their kickers
CREATE POLICY "Users can view comments for their kickers"
ON kopecht.match_comments FOR SELECT
USING (
    EXISTS (
        SELECT 1 FROM kopecht.player
        WHERE kopecht.player.kicker_id = kopecht.match_comments.kicker_id
        AND kopecht.player.user_id = auth.uid()
    )
);

-- Users can insert comments if they have a player in that kicker
CREATE POLICY "Users can insert comments"
ON kopecht.match_comments FOR INSERT
WITH CHECK (
    EXISTS (
        SELECT 1 FROM kopecht.player
        WHERE kopecht.player.kicker_id = kopecht.match_comments.kicker_id
        AND kopecht.player.user_id = auth.uid()
        AND kopecht.player.id = kopecht.match_comments.player_id
    )
);

-- Users can update their own comments
CREATE POLICY "Users can update own comments"
ON kopecht.match_comments FOR UPDATE
USING (
    EXISTS (
        SELECT 1 FROM kopecht.player
        WHERE kopecht.player.id = kopecht.match_comments.player_id
        AND kopecht.player.user_id = auth.uid()
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1 FROM kopecht.player
        WHERE kopecht.player.id = kopecht.match_comments.player_id
        AND kopecht.player.user_id = auth.uid()
    )
);

-- Only kicker admin can delete comments
CREATE POLICY "Admins can delete comments"
ON kopecht.match_comments FOR DELETE
USING (
    EXISTS (
        SELECT 1 FROM kopecht.kicker
        WHERE kopecht.kicker.id = kopecht.match_comments.kicker_id
        AND kopecht.kicker.admin = auth.uid()
    )
);

-- 6. RLS Policies for match_reactions

-- Users can view reactions for matches in their kickers
CREATE POLICY "Users can view match reactions"
ON kopecht.match_reactions FOR SELECT
USING (
    EXISTS (
        SELECT 1 FROM kopecht.player
        WHERE kopecht.player.kicker_id = kopecht.match_reactions.kicker_id
        AND kopecht.player.user_id = auth.uid()
    )
);

-- Users can insert reactions if they have a player in that kicker
CREATE POLICY "Users can insert match reactions"
ON kopecht.match_reactions FOR INSERT
WITH CHECK (
    EXISTS (
        SELECT 1 FROM kopecht.player
        WHERE kopecht.player.kicker_id = kopecht.match_reactions.kicker_id
        AND kopecht.player.user_id = auth.uid()
        AND kopecht.player.id = kopecht.match_reactions.player_id
    )
);

-- Users can delete their own reactions
CREATE POLICY "Users can delete own match reactions"
ON kopecht.match_reactions FOR DELETE
USING (
    EXISTS (
        SELECT 1 FROM kopecht.player
        WHERE kopecht.player.id = kopecht.match_reactions.player_id
        AND kopecht.player.user_id = auth.uid()
    )
);

-- 7. RLS Policies for comment_reactions

-- Users can view comment reactions for their kickers
CREATE POLICY "Users can view comment reactions"
ON kopecht.comment_reactions FOR SELECT
USING (
    EXISTS (
        SELECT 1 FROM kopecht.player
        WHERE kopecht.player.kicker_id = kopecht.comment_reactions.kicker_id
        AND kopecht.player.user_id = auth.uid()
    )
);

-- Users can insert comment reactions if they have a player in that kicker
CREATE POLICY "Users can insert comment reactions"
ON kopecht.comment_reactions FOR INSERT
WITH CHECK (
    EXISTS (
        SELECT 1 FROM kopecht.player
        WHERE kopecht.player.kicker_id = kopecht.comment_reactions.kicker_id
        AND kopecht.player.user_id = auth.uid()
        AND kopecht.player.id = kopecht.comment_reactions.player_id
    )
);

-- Users can delete their own comment reactions
CREATE POLICY "Users can delete own comment reactions"
ON kopecht.comment_reactions FOR DELETE
USING (
    EXISTS (
        SELECT 1 FROM kopecht.player
        WHERE kopecht.player.id = kopecht.comment_reactions.player_id
        AND kopecht.player.user_id = auth.uid()
    )
);

-- 8. Enable realtime for the tables
ALTER PUBLICATION supabase_realtime ADD TABLE kopecht.match_comments;
ALTER PUBLICATION supabase_realtime ADD TABLE kopecht.match_reactions;
ALTER PUBLICATION supabase_realtime ADD TABLE kopecht.comment_reactions;
