-- Migration: Create chat_messages, chat_reactions, and chat_typing tables
-- For kicker-wide chat with whisper support, reactions, and typing indicators

SET search_path TO kopecht;

-- 1. Create chat_messages table
CREATE TABLE IF NOT EXISTS kopecht.chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    edited_at TIMESTAMPTZ,
    player_id BIGINT NOT NULL REFERENCES kopecht.player(id) ON DELETE CASCADE,
    kicker_id BIGINT NOT NULL REFERENCES kopecht.kicker(id) ON DELETE CASCADE,
    content VARCHAR(500) NOT NULL,
    -- For reply feature (one level deep)
    reply_to_id BIGINT REFERENCES kopecht.chat_messages(id) ON DELETE SET NULL,
    -- For whisper/private messages (NULL = public message)
    recipient_id BIGINT REFERENCES kopecht.player(id) ON DELETE CASCADE
);

-- Create indexes for chat_messages
CREATE INDEX IF NOT EXISTS idx_chat_messages_kicker_id ON kopecht.chat_messages(kicker_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_player_id ON kopecht.chat_messages(player_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_created_at ON kopecht.chat_messages(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_chat_messages_recipient_id ON kopecht.chat_messages(recipient_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_reply_to_id ON kopecht.chat_messages(reply_to_id);

-- 2. Create chat_reactions table
CREATE TABLE IF NOT EXISTS kopecht.chat_reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    message_id BIGINT NOT NULL REFERENCES kopecht.chat_messages(id) ON DELETE CASCADE,
    player_id BIGINT NOT NULL REFERENCES kopecht.player(id) ON DELETE CASCADE,
    kicker_id BIGINT NOT NULL REFERENCES kopecht.kicker(id) ON DELETE CASCADE,
    reaction_type TEXT NOT NULL,
    UNIQUE(message_id, player_id, reaction_type)
);

-- Create indexes for chat_reactions
CREATE INDEX IF NOT EXISTS idx_chat_reactions_message_id ON kopecht.chat_reactions(message_id);
CREATE INDEX IF NOT EXISTS idx_chat_reactions_player_id ON kopecht.chat_reactions(player_id);

-- 3. Create chat_typing table for typing indicators
CREATE TABLE IF NOT EXISTS kopecht.chat_typing (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL REFERENCES kopecht.player(id) ON DELETE CASCADE,
    kicker_id BIGINT NOT NULL REFERENCES kopecht.kicker(id) ON DELETE CASCADE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(player_id, kicker_id)
);

-- Create indexes for chat_typing
CREATE INDEX IF NOT EXISTS idx_chat_typing_kicker_id ON kopecht.chat_typing(kicker_id);
CREATE INDEX IF NOT EXISTS idx_chat_typing_updated_at ON kopecht.chat_typing(updated_at);

-- 4. Enable Row Level Security
ALTER TABLE kopecht.chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE kopecht.chat_reactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE kopecht.chat_typing ENABLE ROW LEVEL SECURITY;

-- 5. RLS Policies for chat_messages

-- Users can view public messages OR whispers where they are sender/recipient
CREATE POLICY "Users can view chat messages"
ON kopecht.chat_messages FOR SELECT
USING (
    EXISTS (
        SELECT 1 FROM kopecht.player
        WHERE kopecht.player.kicker_id = kopecht.chat_messages.kicker_id
        AND kopecht.player.user_id = auth.uid()
    )
    AND (
        -- Public message (no recipient)
        kopecht.chat_messages.recipient_id IS NULL
        OR
        -- User is the sender
        EXISTS (
            SELECT 1 FROM kopecht.player
            WHERE kopecht.player.id = kopecht.chat_messages.player_id
            AND kopecht.player.user_id = auth.uid()
        )
        OR
        -- User is the recipient
        EXISTS (
            SELECT 1 FROM kopecht.player
            WHERE kopecht.player.id = kopecht.chat_messages.recipient_id
            AND kopecht.player.user_id = auth.uid()
        )
    )
);

-- Users can insert messages if they have a player in that kicker
CREATE POLICY "Users can insert chat messages"
ON kopecht.chat_messages FOR INSERT
WITH CHECK (
    EXISTS (
        SELECT 1 FROM kopecht.player
        WHERE kopecht.player.kicker_id = kopecht.chat_messages.kicker_id
        AND kopecht.player.user_id = auth.uid()
        AND kopecht.player.id = kopecht.chat_messages.player_id
    )
);

-- Users can update their own messages
CREATE POLICY "Users can update own chat messages"
ON kopecht.chat_messages FOR UPDATE
USING (
    EXISTS (
        SELECT 1 FROM kopecht.player
        WHERE kopecht.player.id = kopecht.chat_messages.player_id
        AND kopecht.player.user_id = auth.uid()
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1 FROM kopecht.player
        WHERE kopecht.player.id = kopecht.chat_messages.player_id
        AND kopecht.player.user_id = auth.uid()
    )
);

-- Only kicker admin can delete messages
CREATE POLICY "Admins can delete chat messages"
ON kopecht.chat_messages FOR DELETE
USING (
    EXISTS (
        SELECT 1 FROM kopecht.kicker
        WHERE kopecht.kicker.id = kopecht.chat_messages.kicker_id
        AND kopecht.kicker.admin = auth.uid()
    )
);

-- 6. RLS Policies for chat_reactions

-- Users can view reactions for messages they can see
CREATE POLICY "Users can view chat reactions"
ON kopecht.chat_reactions FOR SELECT
USING (
    EXISTS (
        SELECT 1 FROM kopecht.player
        WHERE kopecht.player.kicker_id = kopecht.chat_reactions.kicker_id
        AND kopecht.player.user_id = auth.uid()
    )
);

-- Users can insert reactions if they have a player in that kicker
CREATE POLICY "Users can insert chat reactions"
ON kopecht.chat_reactions FOR INSERT
WITH CHECK (
    EXISTS (
        SELECT 1 FROM kopecht.player
        WHERE kopecht.player.kicker_id = kopecht.chat_reactions.kicker_id
        AND kopecht.player.user_id = auth.uid()
        AND kopecht.player.id = kopecht.chat_reactions.player_id
    )
);

-- Users can delete their own reactions
CREATE POLICY "Users can delete own chat reactions"
ON kopecht.chat_reactions FOR DELETE
USING (
    EXISTS (
        SELECT 1 FROM kopecht.player
        WHERE kopecht.player.id = kopecht.chat_reactions.player_id
        AND kopecht.player.user_id = auth.uid()
    )
);

-- 7. RLS Policies for chat_typing

-- Users can view typing status for their kicker
CREATE POLICY "Users can view typing status"
ON kopecht.chat_typing FOR SELECT
USING (
    EXISTS (
        SELECT 1 FROM kopecht.player
        WHERE kopecht.player.kicker_id = kopecht.chat_typing.kicker_id
        AND kopecht.player.user_id = auth.uid()
    )
);

-- Users can insert/update their own typing status
CREATE POLICY "Users can insert typing status"
ON kopecht.chat_typing FOR INSERT
WITH CHECK (
    EXISTS (
        SELECT 1 FROM kopecht.player
        WHERE kopecht.player.kicker_id = kopecht.chat_typing.kicker_id
        AND kopecht.player.user_id = auth.uid()
        AND kopecht.player.id = kopecht.chat_typing.player_id
    )
);

CREATE POLICY "Users can update own typing status"
ON kopecht.chat_typing FOR UPDATE
USING (
    EXISTS (
        SELECT 1 FROM kopecht.player
        WHERE kopecht.player.id = kopecht.chat_typing.player_id
        AND kopecht.player.user_id = auth.uid()
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1 FROM kopecht.player
        WHERE kopecht.player.id = kopecht.chat_typing.player_id
        AND kopecht.player.user_id = auth.uid()
    )
);

-- Users can delete their own typing status
CREATE POLICY "Users can delete own typing status"
ON kopecht.chat_typing FOR DELETE
USING (
    EXISTS (
        SELECT 1 FROM kopecht.player
        WHERE kopecht.player.id = kopecht.chat_typing.player_id
        AND kopecht.player.user_id = auth.uid()
    )
);

-- 8. Enable realtime for the tables
ALTER PUBLICATION supabase_realtime ADD TABLE kopecht.chat_messages;
ALTER PUBLICATION supabase_realtime ADD TABLE kopecht.chat_reactions;
ALTER PUBLICATION supabase_realtime ADD TABLE kopecht.chat_typing;
