-- Migration: Create user_kicker_order table for kicker sorting
-- Schema: public

SET search_path TO public;

-- Table to store user's preferred kicker order
CREATE TABLE IF NOT EXISTS public.user_kicker_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    kicker_id BIGINT NOT NULL REFERENCES public.kicker(id) ON DELETE CASCADE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, kicker_id)
);

-- Index for faster lookups
CREATE INDEX IF NOT EXISTS idx_user_kicker_order_user_id ON public.user_kicker_order(user_id);

-- Function to update kicker order for a user
CREATE OR REPLACE FUNCTION public.update_kicker_order(
    p_user_id UUID,
    p_kicker_ids BIGINT[]
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    i INTEGER;
    v_kicker_id BIGINT;
BEGIN
    -- Loop through the array and upsert each kicker's order
    FOR i IN 1..array_length(p_kicker_ids, 1) LOOP
        v_kicker_id := p_kicker_ids[i];
        
        INSERT INTO public.user_kicker_order (user_id, kicker_id, sort_order, updated_at)
        VALUES (p_user_id, v_kicker_id, i - 1, NOW())
        ON CONFLICT (user_id, kicker_id)
        DO UPDATE SET sort_order = i - 1, updated_at = NOW();
    END LOOP;
END;
$$;

-- Grant execute permission
GRANT EXECUTE ON FUNCTION public.update_kicker_order(UUID, BIGINT[]) TO authenticated;

-- Enable RLS
ALTER TABLE public.user_kicker_order ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can view their own kicker order"
    ON public.user_kicker_order
    FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own kicker order"
    ON public.user_kicker_order
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own kicker order"
    ON public.user_kicker_order
    FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own kicker order"
    ON public.user_kicker_order
    FOR DELETE
    USING (auth.uid() = user_id);
