-- Migration: Create rewards system tables
-- Schema: kopecht

-- ============================================
-- REWARD DEFINITIONS TABLE
-- Stores all available rewards that can be unlocked via achievements
-- ============================================
CREATE TABLE IF NOT EXISTS kopecht.reward_definitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    description TEXT,
    type TEXT NOT NULL CHECK (type IN ('title', 'frame', 'right')),
    -- For titles: 'prefix' means "Title Name", 'suffix' means "Name, Title"
    display_position TEXT CHECK (display_position IN ('prefix', 'suffix')),
    -- The actual value: title text, frame URL, or right identifier
    display_value TEXT NOT NULL,
    -- Achievement that unlocks this reward (NULL = unlocked by default or other means)
    achievement_key TEXT REFERENCES kopecht.achievement_definitions(key),
    icon TEXT,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================
-- PLAYER SELECTED REWARDS TABLE
-- Stores each player's currently active reward per type
-- ============================================
CREATE TABLE IF NOT EXISTS kopecht.player_selected_rewards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL REFERENCES kopecht.player(id) ON DELETE CASCADE,
    reward_type TEXT NOT NULL CHECK (reward_type IN ('title', 'frame')),
    reward_id BIGINT REFERENCES kopecht.reward_definitions(id) ON DELETE SET NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT player_selected_rewards_unique UNIQUE (player_id, reward_type)
);

-- ============================================
-- INDEXES
-- ============================================
CREATE INDEX IF NOT EXISTS idx_reward_definitions_type ON kopecht.reward_definitions(type);
CREATE INDEX IF NOT EXISTS idx_reward_definitions_achievement ON kopecht.reward_definitions(achievement_key);
CREATE INDEX IF NOT EXISTS idx_player_selected_rewards_player ON kopecht.player_selected_rewards(player_id);

-- ============================================
-- RLS POLICIES
-- ============================================
ALTER TABLE kopecht.reward_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE kopecht.player_selected_rewards ENABLE ROW LEVEL SECURITY;

-- Reward definitions: Everyone can read
CREATE POLICY "reward_definitions_select_policy" ON kopecht.reward_definitions
    FOR SELECT USING (true);

-- Reward definitions: Only super admin can insert/update/delete
CREATE POLICY "reward_definitions_insert_policy" ON kopecht.reward_definitions
    FOR INSERT WITH CHECK (auth.uid() = 'caeedd2f-5809-41ff-8a79-0c4c64836d2b'::uuid);

CREATE POLICY "reward_definitions_update_policy" ON kopecht.reward_definitions
    FOR UPDATE USING (auth.uid() = 'caeedd2f-5809-41ff-8a79-0c4c64836d2b'::uuid);

CREATE POLICY "reward_definitions_delete_policy" ON kopecht.reward_definitions
    FOR DELETE USING (auth.uid() = 'caeedd2f-5809-41ff-8a79-0c4c64836d2b'::uuid);

-- Player selected rewards: Players can manage their own selections
CREATE POLICY "player_selected_rewards_select_policy" ON kopecht.player_selected_rewards
    FOR SELECT USING (true);

CREATE POLICY "player_selected_rewards_insert_policy" ON kopecht.player_selected_rewards
    FOR INSERT WITH CHECK (
        player_id IN (SELECT id FROM kopecht.player WHERE user_id = auth.uid())
    );

CREATE POLICY "player_selected_rewards_update_policy" ON kopecht.player_selected_rewards
    FOR UPDATE USING (
        player_id IN (SELECT id FROM kopecht.player WHERE user_id = auth.uid())
    );

CREATE POLICY "player_selected_rewards_delete_policy" ON kopecht.player_selected_rewards
    FOR DELETE USING (
        player_id IN (SELECT id FROM kopecht.player WHERE user_id = auth.uid())
    );

-- ============================================
-- RPC: Get player with rewards
-- Returns player data along with their selected title and frame
-- ============================================
CREATE OR REPLACE FUNCTION kopecht.get_player_with_rewards(p_player_id BIGINT)
RETURNS TABLE (
    player_id BIGINT,
    player_name TEXT,
    avatar TEXT,
    title_id BIGINT,
    title_name TEXT,
    title_display_position TEXT,
    title_display_value TEXT,
    frame_id BIGINT,
    frame_name TEXT,
    frame_display_value TEXT
) 
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        p.id AS player_id,
        p.name AS player_name,
        p.avatar,
        t.id AS title_id,
        t.name AS title_name,
        t.display_position AS title_display_position,
        t.display_value AS title_display_value,
        f.id AS frame_id,
        f.name AS frame_name,
        f.display_value AS frame_display_value
    FROM kopecht.player p
    LEFT JOIN kopecht.player_selected_rewards psr_title 
        ON p.id = psr_title.player_id AND psr_title.reward_type = 'title'
    LEFT JOIN kopecht.reward_definitions t 
        ON psr_title.reward_id = t.id
    LEFT JOIN kopecht.player_selected_rewards psr_frame 
        ON p.id = psr_frame.player_id AND psr_frame.reward_type = 'frame'
    LEFT JOIN kopecht.reward_definitions f 
        ON psr_frame.reward_id = f.id
    WHERE p.id = p_player_id;
END;
$$;

-- ============================================
-- RPC: Get unlocked rewards for a player
-- Returns all rewards the player has unlocked (via achievements)
-- ============================================
CREATE OR REPLACE FUNCTION kopecht.get_player_unlocked_rewards(p_player_id BIGINT)
RETURNS TABLE (
    reward_id BIGINT,
    reward_key TEXT,
    reward_name TEXT,
    reward_description TEXT,
    reward_type TEXT,
    display_position TEXT,
    display_value TEXT,
    icon TEXT,
    achievement_key TEXT,
    achievement_name TEXT,
    is_selected BOOLEAN
) 
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        rd.id AS reward_id,
        rd.key AS reward_key,
        rd.name AS reward_name,
        rd.description AS reward_description,
        rd.type AS reward_type,
        rd.display_position,
        rd.display_value,
        rd.icon,
        rd.achievement_key,
        ad.name AS achievement_name,
        CASE WHEN psr.id IS NOT NULL THEN true ELSE false END AS is_selected
    FROM kopecht.reward_definitions rd
    -- Join to get the achievement definition name
    LEFT JOIN kopecht.achievement_definitions ad ON rd.achievement_key = ad.key
    -- Check if this reward is currently selected
    LEFT JOIN kopecht.player_selected_rewards psr 
        ON psr.player_id = p_player_id 
        AND psr.reward_id = rd.id 
        AND psr.reward_type = rd.type
    WHERE 
        -- Reward has no achievement requirement (always unlocked)
        rd.achievement_key IS NULL
        OR
        -- Player has unlocked the achievement
        EXISTS (
            SELECT 1 
            FROM kopecht.player_achievements pa
            JOIN kopecht.achievement_definitions ad2 ON pa.achievement_id = ad2.id
            WHERE pa.player_id = p_player_id 
            AND ad2.key = rd.achievement_key
        )
    ORDER BY rd.type, rd.sort_order;
END;
$$;

-- ============================================
-- RPC: Update player selected reward
-- ============================================
CREATE OR REPLACE FUNCTION kopecht.update_player_selected_reward(
    p_player_id BIGINT,
    p_reward_type TEXT,
    p_reward_id BIGINT DEFAULT NULL
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_user_id UUID;
BEGIN
    -- Get the user_id for the player
    SELECT user_id INTO v_user_id FROM kopecht.player WHERE id = p_player_id;
    
    -- Check if the current user owns this player
    IF v_user_id != auth.uid() THEN
        RAISE EXCEPTION 'Not authorized to update rewards for this player';
    END IF;

    -- If reward_id is NULL, remove the selection
    IF p_reward_id IS NULL THEN
        DELETE FROM kopecht.player_selected_rewards
        WHERE player_id = p_player_id AND reward_type = p_reward_type;
    ELSE
        -- Verify the player has unlocked this reward
        IF NOT EXISTS (
            SELECT 1 FROM kopecht.reward_definitions rd
            WHERE rd.id = p_reward_id
            AND (
                rd.achievement_key IS NULL
                OR EXISTS (
                    SELECT 1 
                    FROM kopecht.player_achievements pa
                    JOIN kopecht.achievement_definitions ad ON pa.achievement_id = ad.id
                    WHERE pa.player_id = p_player_id 
                    AND ad.key = rd.achievement_key
                )
            )
        ) THEN
            RAISE EXCEPTION 'Reward not unlocked';
        END IF;

        -- Upsert the selection
        INSERT INTO kopecht.player_selected_rewards (player_id, reward_type, reward_id, updated_at)
        VALUES (p_player_id, p_reward_type, p_reward_id, NOW())
        ON CONFLICT (player_id, reward_type) 
        DO UPDATE SET reward_id = p_reward_id, updated_at = NOW();
    END IF;

    RETURN true;
END;
$$;

-- ============================================
-- INITIAL REWARD DATA
-- Example titles linked to achievements
-- ============================================

-- Titles
INSERT INTO kopecht.reward_definitions (key, name, description, type, display_position, display_value, achievement_key, icon, sort_order) VALUES
-- Carry achievement unlocks "Carry" title
('title_carry', 'Carry', 'Show everyone you carry the team', 'title', 'prefix', 'Carry', 'carry_2on2', '💪', 10),

-- Giant Slayer achievement unlocks title
('title_giant_slayer', 'Giant Slayer', 'Display your prowess against stronger opponents', 'title', 'suffix', 'the Giant Slayer', 'giant_slayer_1on1', '⚔️', 20),

-- Win streak achievements
('title_unstoppable', 'Unstoppable', 'For those on an incredible winning streak', 'title', 'prefix', 'Unstoppable', 'win_streak_10_1on1', '🔥', 30),

-- Perfect games
('title_perfectionist', 'Perfectionist', 'For achieving perfect victories', 'title', 'suffix', 'the Perfectionist', 'perfect_wins_10', '✨', 40),

-- Speed demon - blitzkrieg is the fast win achievement
('title_speedster', 'Speedster', 'For lightning-fast victories', 'title', 'prefix', 'Speedster', 'blitzkrieg_1on1', '⚡', 50),

-- Comeback king
('title_comeback_king', 'Comeback King', 'For those who never give up', 'title', 'suffix', 'the Comeback King', 'miracle_comeback', '👑', 60),

-- Veteran title
('title_veteran', 'Veteran', 'For experienced players', 'title', 'prefix', 'Veteran', 'matches_1on1_100', '🎖️', 70),

-- Champion
('title_champion', 'Champion', 'For season champions', 'title', 'suffix', 'the Champion', 'season_champion_1on1', '🏆', 80),

-- Secret achievements - own goal specialist
('title_own_goal_master', 'Own Goal Specialist', 'Embrace your unique playstyle', 'title', 'suffix', 'the Own Goal Specialist', 'own_goals_alltime_100', '🙃', 90),

-- MMR Below 700 - for the meme
('title_underdog', 'Underdog', 'Started from the bottom', 'title', 'prefix', 'Underdog', 'mmr_below_700_1on1', '🐢', 100),

-- Final nail - scoring own goal at 1-9
('title_final_nail', 'Final Nail', 'Master of unfortunate timing', 'title', 'suffix', 'the Final Nail', 'final_nail_1on1', '⚰️', 110)

ON CONFLICT (key) DO NOTHING;

-- Grant execute permissions
GRANT EXECUTE ON FUNCTION kopecht.get_player_with_rewards(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION kopecht.get_player_unlocked_rewards(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION kopecht.update_player_selected_reward(BIGINT, TEXT, BIGINT) TO authenticated;
