-- Migration: Create chat_read_status table for tracking unread messages
-- Used for notification badges (iOS, Android, Browser tabs)

SET search_path TO kopecht;

-- 1. Create chat_read_status table
-- Tracks when a user last read messages per kicker
CREATE TABLE IF NOT EXISTS kopecht.chat_read_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    kicker_id BIGINT NOT NULL REFERENCES kopecht.kicker(id) ON DELETE CASCADE,
    last_read_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(user_id, kicker_id)
);

-- Create indexes for chat_read_status
CREATE INDEX IF NOT EXISTS idx_chat_read_status_user_id ON kopecht.chat_read_status(user_id);
CREATE INDEX IF NOT EXISTS idx_chat_read_status_kicker_id ON kopecht.chat_read_status(kicker_id);
CREATE INDEX IF NOT EXISTS idx_chat_read_status_last_read_at ON kopecht.chat_read_status(last_read_at);

-- 2. Enable Row Level Security
ALTER TABLE kopecht.chat_read_status ENABLE ROW LEVEL SECURITY;

-- 3. RLS Policies for chat_read_status

-- Users can view their own read status
CREATE POLICY "Users can view own read status"
ON kopecht.chat_read_status FOR SELECT
USING (auth.uid() = user_id);

-- Users can insert their own read status
CREATE POLICY "Users can insert own read status"
ON kopecht.chat_read_status FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- Users can update their own read status
CREATE POLICY "Users can update own read status"
ON kopecht.chat_read_status FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Users can delete their own read status
CREATE POLICY "Users can delete own read status"
ON kopecht.chat_read_status FOR DELETE
USING (auth.uid() = user_id);

-- 4. Create function to update last_read_at and updated_at
CREATE OR REPLACE FUNCTION kopecht.update_chat_read_status(p_kicker_id BIGINT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    INSERT INTO kopecht.chat_read_status (user_id, kicker_id, last_read_at, updated_at)
    VALUES (auth.uid(), p_kicker_id, NOW(), NOW())
    ON CONFLICT (user_id, kicker_id)
    DO UPDATE SET 
        last_read_at = NOW(),
        updated_at = NOW();
END;
$$;

-- 5. Create function to get unread count per kicker for current user
CREATE OR REPLACE FUNCTION kopecht.get_unread_count_per_kicker()
RETURNS TABLE(kicker_id BIGINT, unread_count BIGINT)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        p.kicker_id,
        COUNT(cm.id)::BIGINT as unread_count
    FROM kopecht.player p
    LEFT JOIN kopecht.chat_read_status crs ON crs.kicker_id = p.kicker_id AND crs.user_id = auth.uid()
    LEFT JOIN kopecht.chat_messages cm ON cm.kicker_id = p.kicker_id
        AND cm.created_at > COALESCE(crs.last_read_at, '1970-01-01'::TIMESTAMPTZ)
        AND cm.player_id != p.id  -- Don't count own messages
        AND (
            -- Public messages
            cm.recipient_id IS NULL
            OR
            -- Whispers to this user
            cm.recipient_id = p.id
        )
    WHERE p.user_id = auth.uid()
    GROUP BY p.kicker_id;
END;
$$;

-- 6. Create function to get total unread count across all kickers for current user
CREATE OR REPLACE FUNCTION kopecht.get_total_unread_count()
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    total BIGINT;
BEGIN
    SELECT COALESCE(SUM(unread_count), 0) INTO total
    FROM kopecht.get_unread_count_per_kicker();
    
    RETURN total;
END;
$$;

-- 7. Create function to get unread count for a specific user (used by edge function for iOS badge)
CREATE OR REPLACE FUNCTION kopecht.get_unread_count_for_user(p_user_id UUID)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    total BIGINT;
BEGIN
    SELECT COALESCE(SUM(cnt), 0) INTO total
    FROM (
        SELECT COUNT(cm.id) as cnt
        FROM kopecht.player p
        LEFT JOIN kopecht.chat_read_status crs ON crs.kicker_id = p.kicker_id AND crs.user_id = p_user_id
        LEFT JOIN kopecht.chat_messages cm ON cm.kicker_id = p.kicker_id
            AND cm.created_at > COALESCE(crs.last_read_at, '1970-01-01'::TIMESTAMPTZ)
            AND cm.player_id != p.id
            AND (
                cm.recipient_id IS NULL
                OR
                cm.recipient_id = p.id
            )
        WHERE p.user_id = p_user_id
        GROUP BY p.kicker_id
    ) sub;
    
    RETURN COALESCE(total, 0);
END;
$$;

-- 8. Enable realtime for the table
ALTER PUBLICATION supabase_realtime ADD TABLE kopecht.chat_read_status;

-- 9. Grant execute permissions on functions
GRANT EXECUTE ON FUNCTION kopecht.update_chat_read_status(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION kopecht.get_unread_count_per_kicker() TO authenticated;
GRANT EXECUTE ON FUNCTION kopecht.get_total_unread_count() TO authenticated;
GRANT EXECUTE ON FUNCTION kopecht.get_unread_count_for_user(UUID) TO service_role;
