-- Migration: Create comment_read_status table for tracking unread match comments
-- Used for notification badges in the Match Comments tab

SET search_path TO public;

-- 1. Create comment_read_status table
-- Tracks when a user last read match comments per kicker
CREATE TABLE IF NOT EXISTS comment_read_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    kicker_id BIGINT NOT NULL REFERENCES kicker(id) ON DELETE CASCADE,
    last_read_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(user_id, kicker_id)
);

-- Create indexes for comment_read_status
CREATE INDEX IF NOT EXISTS idx_comment_read_status_user_id ON comment_read_status(user_id);
CREATE INDEX IF NOT EXISTS idx_comment_read_status_kicker_id ON comment_read_status(kicker_id);
CREATE INDEX IF NOT EXISTS idx_comment_read_status_last_read_at ON comment_read_status(last_read_at);

-- 2. Enable Row Level Security
ALTER TABLE comment_read_status ENABLE ROW LEVEL SECURITY;

-- 3. RLS Policies for comment_read_status

-- Users can view their own read status
CREATE POLICY "Users can view own comment read status"
ON comment_read_status FOR SELECT
USING (auth.uid() = user_id);

-- Users can insert their own read status
CREATE POLICY "Users can insert own comment read status"
ON comment_read_status FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- Users can update their own read status
CREATE POLICY "Users can update own comment read status"
ON comment_read_status FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Users can delete their own read status
CREATE POLICY "Users can delete own comment read status"
ON comment_read_status FOR DELETE
USING (auth.uid() = user_id);

-- 4. Create function to update last_read_at and updated_at
CREATE OR REPLACE FUNCTION update_comment_read_status(p_kicker_id BIGINT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    INSERT INTO comment_read_status (user_id, kicker_id, last_read_at, updated_at)
    VALUES (auth.uid(), p_kicker_id, NOW(), NOW())
    ON CONFLICT (user_id, kicker_id)
    DO UPDATE SET 
        last_read_at = NOW(),
        updated_at = NOW();
END;
$$;

-- 5. Create function to get unread comment count per kicker for current user
CREATE OR REPLACE FUNCTION get_unread_comment_count_per_kicker()
RETURNS TABLE(kicker_id BIGINT, unread_count BIGINT)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        p.kicker_id,
        COUNT(mc.id)::BIGINT as unread_count
    FROM player p
    LEFT JOIN comment_read_status crs ON crs.kicker_id = p.kicker_id AND crs.user_id = auth.uid()
    LEFT JOIN match_comments mc ON mc.kicker_id = p.kicker_id
        AND mc.created_at > COALESCE(crs.last_read_at, '1970-01-01'::TIMESTAMPTZ)
        AND mc.player_id != p.id  -- Don't count own comments
    WHERE p.user_id = auth.uid()
    GROUP BY p.kicker_id;
END;
$$;

-- 6. Create function to get unread comment count for a specific kicker
CREATE OR REPLACE FUNCTION get_unread_comment_count(p_kicker_id BIGINT)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_player_id BIGINT;
    v_last_read_at TIMESTAMPTZ;
    v_count BIGINT;
BEGIN
    -- Get the player ID for this user in this kicker
    SELECT id INTO v_player_id
    FROM player
    WHERE user_id = auth.uid() AND kicker_id = p_kicker_id;
    
    IF v_player_id IS NULL THEN
        RETURN 0;
    END IF;
    
    -- Get last read timestamp
    SELECT last_read_at INTO v_last_read_at
    FROM comment_read_status
    WHERE user_id = auth.uid() AND kicker_id = p_kicker_id;
    
    -- Count unread comments
    SELECT COUNT(*)::BIGINT INTO v_count
    FROM match_comments mc
    WHERE mc.kicker_id = p_kicker_id
        AND mc.created_at > COALESCE(v_last_read_at, '1970-01-01'::TIMESTAMPTZ)
        AND mc.player_id != v_player_id;  -- Don't count own comments
    
    RETURN COALESCE(v_count, 0);
END;
$$;

-- 7. Enable realtime for the table
ALTER PUBLICATION supabase_realtime ADD TABLE comment_read_status;

-- 8. Grant execute permissions on functions
GRANT EXECUTE ON FUNCTION update_comment_read_status(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION get_unread_comment_count_per_kicker() TO authenticated;
GRANT EXECUTE ON FUNCTION get_unread_comment_count(BIGINT) TO authenticated;
