-- Migration: Create Achievement System Tables
-- Schema: kopecht

SET search_path TO kopecht;

-- 1. Achievement Categories
CREATE TABLE IF NOT EXISTS kopecht.achievement_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    icon TEXT,
    sort_order INT NOT NULL DEFAULT 0,
    kicker_id BIGINT NOT NULL REFERENCES kopecht.kicker(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT achievement_categories_key_kicker_unique UNIQUE (key, kicker_id)
);

-- 2. Achievement Definitions
CREATE TABLE IF NOT EXISTS kopecht.achievement_definitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    category_id BIGINT NOT NULL REFERENCES kopecht.achievement_categories(id) ON DELETE CASCADE,
    trigger_event TEXT NOT NULL, -- 'MATCH_ENDED', 'GOAL_SCORED', 'SEASON_ENDED'
    condition JSONB NOT NULL DEFAULT '{}',
    points INT NOT NULL DEFAULT 10,
    icon TEXT,
    is_hidden BOOLEAN NOT NULL DEFAULT FALSE,
    is_repeatable BOOLEAN NOT NULL DEFAULT FALSE,
    max_progress INT NOT NULL DEFAULT 1,
    season_id BIGINT REFERENCES kopecht.seasons(id) ON DELETE SET NULL,
    parent_id BIGINT REFERENCES kopecht.achievement_definitions(id) ON DELETE SET NULL,
    sort_order INT NOT NULL DEFAULT 0,
    kicker_id BIGINT NOT NULL REFERENCES kopecht.kicker(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT achievement_definitions_key_kicker_unique UNIQUE (key, kicker_id)
);

-- 3. Player Achievement Progress (for tracking progress towards achievements)
CREATE TABLE IF NOT EXISTS kopecht.player_achievement_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL REFERENCES kopecht.player(id) ON DELETE CASCADE,
    achievement_id BIGINT NOT NULL REFERENCES kopecht.achievement_definitions(id) ON DELETE CASCADE,
    current_progress INT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT player_achievement_progress_unique UNIQUE (player_id, achievement_id)
);

-- 4. Player Achievements (unlocked achievements)
CREATE TABLE IF NOT EXISTS kopecht.player_achievements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL REFERENCES kopecht.player(id) ON DELETE CASCADE,
    achievement_id BIGINT NOT NULL REFERENCES kopecht.achievement_definitions(id) ON DELETE CASCADE,
    unlocked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    times_completed INT NOT NULL DEFAULT 1,
    season_id BIGINT REFERENCES kopecht.seasons(id) ON DELETE SET NULL,
    match_id BIGINT REFERENCES kopecht.matches(id) ON DELETE SET NULL,
    CONSTRAINT player_achievements_unique UNIQUE (player_id, achievement_id, season_id)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_achievement_categories_kicker ON kopecht.achievement_categories(kicker_id);
CREATE INDEX IF NOT EXISTS idx_achievement_definitions_kicker ON kopecht.achievement_definitions(kicker_id);
CREATE INDEX IF NOT EXISTS idx_achievement_definitions_trigger ON kopecht.achievement_definitions(trigger_event);
CREATE INDEX IF NOT EXISTS idx_achievement_definitions_category ON kopecht.achievement_definitions(category_id);
CREATE INDEX IF NOT EXISTS idx_achievement_definitions_parent ON kopecht.achievement_definitions(parent_id);
CREATE INDEX IF NOT EXISTS idx_achievement_definitions_season ON kopecht.achievement_definitions(season_id);
CREATE INDEX IF NOT EXISTS idx_player_achievement_progress_player ON kopecht.player_achievement_progress(player_id);
CREATE INDEX IF NOT EXISTS idx_player_achievement_progress_achievement ON kopecht.player_achievement_progress(achievement_id);
CREATE INDEX IF NOT EXISTS idx_player_achievements_player ON kopecht.player_achievements(player_id);
CREATE INDEX IF NOT EXISTS idx_player_achievements_achievement ON kopecht.player_achievements(achievement_id);
CREATE INDEX IF NOT EXISTS idx_player_achievements_season ON kopecht.player_achievements(season_id);
CREATE INDEX IF NOT EXISTS idx_player_achievements_unlocked ON kopecht.player_achievements(unlocked_at DESC);

-- Enable Row Level Security
ALTER TABLE kopecht.achievement_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE kopecht.achievement_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE kopecht.player_achievement_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE kopecht.player_achievements ENABLE ROW LEVEL SECURITY;

-- RLS Policies for achievement_categories
CREATE POLICY "Users can view achievement categories for their kickers"
    ON kopecht.achievement_categories FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM kopecht.player p
            WHERE p.kicker_id = achievement_categories.kicker_id
            AND p.user_id = auth.uid()
        )
    );

CREATE POLICY "Admins can manage achievement categories"
    ON kopecht.achievement_categories FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM kopecht.kicker k
            WHERE k.id = achievement_categories.kicker_id
            AND k.admin = auth.uid()
        )
    );

-- RLS Policies for achievement_definitions
CREATE POLICY "Users can view achievement definitions for their kickers"
    ON kopecht.achievement_definitions FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM kopecht.player p
            WHERE p.kicker_id = achievement_definitions.kicker_id
            AND p.user_id = auth.uid()
        )
        AND (
            is_hidden = FALSE
            OR EXISTS (
                SELECT 1 FROM kopecht.player_achievements pa
                WHERE pa.achievement_id = achievement_definitions.id
                AND pa.player_id IN (
                    SELECT id FROM kopecht.player WHERE user_id = auth.uid()
                )
            )
        )
    );

CREATE POLICY "Admins can view all achievement definitions"
    ON kopecht.achievement_definitions FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM kopecht.kicker k
            WHERE k.id = achievement_definitions.kicker_id
            AND k.admin = auth.uid()
        )
    );

CREATE POLICY "Admins can manage achievement definitions"
    ON kopecht.achievement_definitions FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM kopecht.kicker k
            WHERE k.id = achievement_definitions.kicker_id
            AND k.admin = auth.uid()
        )
    );

-- RLS Policies for player_achievement_progress
CREATE POLICY "Users can view their own achievement progress"
    ON kopecht.player_achievement_progress FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM kopecht.player p
            WHERE p.id = player_achievement_progress.player_id
            AND p.user_id = auth.uid()
        )
    );

CREATE POLICY "Service role can manage all progress"
    ON kopecht.player_achievement_progress FOR ALL
    USING (auth.role() = 'service_role');

-- RLS Policies for player_achievements
CREATE POLICY "Users can view achievements for players in their kickers"
    ON kopecht.player_achievements FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM kopecht.player p
            JOIN kopecht.player p2 ON p.kicker_id = p2.kicker_id
            WHERE p2.id = player_achievements.player_id
            AND p.user_id = auth.uid()
        )
    );

CREATE POLICY "Service role can manage all achievements"
    ON kopecht.player_achievements FOR ALL
    USING (auth.role() = 'service_role');

-- Function to update achievement_definitions updated_at
CREATE OR REPLACE FUNCTION kopecht.update_achievement_definition_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger for updated_at
CREATE TRIGGER update_achievement_definitions_updated_at
    BEFORE UPDATE ON kopecht.achievement_definitions
    FOR EACH ROW
    EXECUTE FUNCTION kopecht.update_achievement_definition_updated_at();

-- Function to update player_achievement_progress updated_at
CREATE OR REPLACE FUNCTION kopecht.update_achievement_progress_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger for progress updated_at
CREATE TRIGGER update_player_achievement_progress_updated_at
    BEFORE UPDATE ON kopecht.player_achievement_progress
    FOR EACH ROW
    EXECUTE FUNCTION kopecht.update_achievement_progress_updated_at();

-- Enable realtime for player_achievements (for toast notifications)
ALTER PUBLICATION supabase_realtime ADD TABLE kopecht.player_achievements;
