-- Migration: Create user_permissions table for feature-based access control
-- Allows admins to grant/revoke permissions to users within a kicker

SET search_path TO public;

-- 1. Create user_permissions table
CREATE TABLE IF NOT EXISTS public.user_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    kicker_id BIGINT NOT NULL REFERENCES public.kicker(id) ON DELETE CASCADE,
    permission_type TEXT NOT NULL,
    granted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    granted_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    UNIQUE(user_id, kicker_id, permission_type)
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_user_permissions_user_id ON public.user_permissions(user_id);
CREATE INDEX IF NOT EXISTS idx_user_permissions_kicker_id ON public.user_permissions(kicker_id);
CREATE INDEX IF NOT EXISTS idx_user_permissions_type ON public.user_permissions(permission_type);

-- 2. Enable Row Level Security
ALTER TABLE public.user_permissions ENABLE ROW LEVEL SECURITY;

-- 3. RLS Policies

-- All authenticated users in the kicker can view permissions
CREATE POLICY "Users can view permissions in their kicker"
ON public.user_permissions FOR SELECT
USING (
    EXISTS (
        SELECT 1 FROM public.player
        WHERE public.player.kicker_id = public.user_permissions.kicker_id
        AND public.player.user_id = auth.uid()
    )
);

-- Only kicker admin can insert permissions
CREATE POLICY "Admin can insert permissions"
ON public.user_permissions FOR INSERT
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.kicker
        WHERE public.kicker.id = public.user_permissions.kicker_id
        AND public.kicker.admin = auth.uid()
    )
);

-- Only kicker admin can update permissions
CREATE POLICY "Admin can update permissions"
ON public.user_permissions FOR UPDATE
USING (
    EXISTS (
        SELECT 1 FROM public.kicker
        WHERE public.kicker.id = public.user_permissions.kicker_id
        AND public.kicker.admin = auth.uid()
    )
);

-- Only kicker admin can delete permissions
CREATE POLICY "Admin can delete permissions"
ON public.user_permissions FOR DELETE
USING (
    EXISTS (
        SELECT 1 FROM public.kicker
        WHERE public.kicker.id = public.user_permissions.kicker_id
        AND public.kicker.admin = auth.uid()
    )
);

-- 4. Create helper function to check if user has a permission
CREATE OR REPLACE FUNCTION public.has_permission(
    p_user_id UUID,
    p_kicker_id BIGINT,
    p_permission_type TEXT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM public.user_permissions
        WHERE user_id = p_user_id
        AND kicker_id = p_kicker_id
        AND permission_type = p_permission_type
    );
END;
$$;

-- 5. Create function to get all permissions for a user in a kicker
CREATE OR REPLACE FUNCTION public.get_user_permissions(
    p_user_id UUID,
    p_kicker_id BIGINT
)
RETURNS TABLE(permission_type TEXT, granted_at TIMESTAMPTZ)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT up.permission_type, up.granted_at
    FROM public.user_permissions up
    WHERE up.user_id = p_user_id
    AND up.kicker_id = p_kicker_id;
END;
$$;

-- 6. Create function to get all users with their permissions in a kicker
CREATE OR REPLACE FUNCTION public.get_kicker_permissions(p_kicker_id BIGINT)
RETURNS TABLE(
    user_id UUID,
    player_id BIGINT,
    player_name TEXT,
    player_avatar TEXT,
    permission_type TEXT,
    granted_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        p.user_id,
        p.id as player_id,
        p.name as player_name,
        p.avatar as player_avatar,
        up.permission_type,
        up.granted_at
    FROM public.player p
    LEFT JOIN public.user_permissions up 
        ON p.user_id = up.user_id 
        AND up.kicker_id = p_kicker_id
    WHERE p.kicker_id = p_kicker_id
    ORDER BY p.name;
END;
$$;

-- 7. Create function to grant a permission
CREATE OR REPLACE FUNCTION public.grant_permission(
    p_user_id UUID,
    p_kicker_id BIGINT,
    p_permission_type TEXT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    -- Check if caller is admin
    IF NOT EXISTS (
        SELECT 1 FROM public.kicker
        WHERE id = p_kicker_id AND admin = auth.uid()
    ) THEN
        RAISE EXCEPTION 'Only kicker admin can grant permissions';
    END IF;

    INSERT INTO public.user_permissions (user_id, kicker_id, permission_type, granted_by)
    VALUES (p_user_id, p_kicker_id, p_permission_type, auth.uid())
    ON CONFLICT (user_id, kicker_id, permission_type) DO NOTHING;
    
    RETURN TRUE;
END;
$$;

-- 8. Create function to revoke a permission
CREATE OR REPLACE FUNCTION public.revoke_permission(
    p_user_id UUID,
    p_kicker_id BIGINT,
    p_permission_type TEXT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    -- Check if caller is admin
    IF NOT EXISTS (
        SELECT 1 FROM public.kicker
        WHERE id = p_kicker_id AND admin = auth.uid()
    ) THEN
        RAISE EXCEPTION 'Only kicker admin can revoke permissions';
    END IF;

    DELETE FROM public.user_permissions
    WHERE user_id = p_user_id
    AND kicker_id = p_kicker_id
    AND permission_type = p_permission_type;
    
    RETURN TRUE;
END;
$$;

