-- Migration: Create team_history table for team MMR tracking (kopecht schema)
-- Similar to player_history, this tracks team MMR changes over time

SET search_path TO kopecht;

-- 1. Create team_history table
CREATE TABLE IF NOT EXISTS kopecht.team_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL REFERENCES kopecht.teams(id) ON DELETE CASCADE,
    match_id BIGINT REFERENCES kopecht.matches(id) ON DELETE SET NULL,
    mmr_before INTEGER NOT NULL,
    mmr_after INTEGER NOT NULL,
    mmr_change INTEGER NOT NULL,
    wins_before INTEGER NOT NULL DEFAULT 0,
    wins_after INTEGER NOT NULL DEFAULT 0,
    losses_before INTEGER NOT NULL DEFAULT 0,
    losses_after INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Create indexes for team_history
CREATE INDEX IF NOT EXISTS idx_team_history_team_id ON kopecht.team_history(team_id);
CREATE INDEX IF NOT EXISTS idx_team_history_match_id ON kopecht.team_history(match_id);
CREATE INDEX IF NOT EXISTS idx_team_history_created_at ON kopecht.team_history(created_at DESC);

-- 3. Create function to record team history after match
CREATE OR REPLACE FUNCTION kopecht.record_team_history()
RETURNS TRIGGER AS $$
BEGIN
    -- Only process if this is a team match (has team1_id and team2_id)
    IF NEW.team1_id IS NOT NULL AND NEW.team2_id IS NOT NULL THEN
        -- Record history for team 1
        INSERT INTO kopecht.team_history (
            team_id,
            match_id,
            mmr_before,
            mmr_after,
            mmr_change,
            wins_before,
            wins_after,
            losses_before,
            losses_after
        )
        SELECT 
            NEW.team1_id,
            NEW.id,
            t.mmr - COALESCE(NEW.mmr_change_team1, 0),
            t.mmr,
            COALESCE(NEW.mmr_change_team1, 0),
            CASE WHEN NEW.score_team1 > NEW.score_team2 THEN t.wins - 1 ELSE t.wins END,
            t.wins,
            CASE WHEN NEW.score_team1 < NEW.score_team2 THEN t.losses - 1 ELSE t.losses END,
            t.losses
        FROM kopecht.teams t
        WHERE t.id = NEW.team1_id;

        -- Record history for team 2
        INSERT INTO kopecht.team_history (
            team_id,
            match_id,
            mmr_before,
            mmr_after,
            mmr_change,
            wins_before,
            wins_after,
            losses_before,
            losses_after
        )
        SELECT 
            NEW.team2_id,
            NEW.id,
            t.mmr - COALESCE(NEW.mmr_change_team2, 0),
            t.mmr,
            COALESCE(NEW.mmr_change_team2, 0),
            CASE WHEN NEW.score_team2 > NEW.score_team1 THEN t.wins - 1 ELSE t.wins END,
            t.wins,
            CASE WHEN NEW.score_team2 < NEW.score_team1 THEN t.losses - 1 ELSE t.losses END,
            t.losses
        FROM kopecht.teams t
        WHERE t.id = NEW.team2_id;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 4. Create trigger for team history on match completion
DROP TRIGGER IF EXISTS trigger_record_team_history ON kopecht.matches;
CREATE TRIGGER trigger_record_team_history
    AFTER UPDATE OF end_time ON kopecht.matches
    FOR EACH ROW
    WHEN (OLD.end_time IS NULL AND NEW.end_time IS NOT NULL)
    EXECUTE FUNCTION kopecht.record_team_history();

-- 5. Enable RLS on team_history
ALTER TABLE kopecht.team_history ENABLE ROW LEVEL SECURITY;

-- 6. Create RLS policies
CREATE POLICY "Team history is viewable by everyone"
    ON kopecht.team_history FOR SELECT
    USING (true);

-- 7. Grant permissions
GRANT SELECT ON kopecht.team_history TO authenticated;
GRANT SELECT ON kopecht.team_history TO anon;

-- 8. Create RPC function to get team MMR history
CREATE OR REPLACE FUNCTION kopecht.get_team_mmr_history(
    p_team_id BIGINT,
    p_limit INTEGER DEFAULT 50
)
RETURNS TABLE (
    id BIGINT,
    match_id BIGINT,
    mmr_before INTEGER,
    mmr_after INTEGER,
    mmr_change INTEGER,
    wins_after INTEGER,
    losses_after INTEGER,
    created_at TIMESTAMPTZ
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        th.id,
        th.match_id,
        th.mmr_before,
        th.mmr_after,
        th.mmr_change,
        th.wins_after,
        th.losses_after,
        th.created_at
    FROM kopecht.team_history th
    WHERE th.team_id = p_team_id
    ORDER BY th.created_at DESC
    LIMIT p_limit;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Grant execute permission
GRANT EXECUTE ON FUNCTION kopecht.get_team_mmr_history(BIGINT, INTEGER) TO authenticated;
GRANT EXECUTE ON FUNCTION kopecht.get_team_mmr_history(BIGINT, INTEGER) TO anon;
