-- Migration: Create team_season_rankings table for team MMR tracking per season
-- Similar to season_rankings for players, this tracks team MMR and stats per season

SET search_path TO kopecht;

-- 1. Create team_season_rankings table
CREATE TABLE IF NOT EXISTS kopecht.team_season_rankings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    team_id BIGINT NOT NULL REFERENCES kopecht.teams(id) ON DELETE CASCADE,
    season_id BIGINT NOT NULL REFERENCES kopecht.seasons(id) ON DELETE CASCADE,
    wins BIGINT NOT NULL DEFAULT 0,
    losses BIGINT NOT NULL DEFAULT 0,
    mmr BIGINT NOT NULL DEFAULT 1000,
    bounty_claimed INTEGER NULL DEFAULT 0,
    
    -- Each team can only have one ranking per season
    CONSTRAINT team_season_rankings_team_id_season_id_key UNIQUE (team_id, season_id)
);

-- 2. Create indexes
CREATE INDEX IF NOT EXISTS team_season_rankings_team_id_idx ON kopecht.team_season_rankings(team_id);
CREATE INDEX IF NOT EXISTS team_season_rankings_season_id_idx ON kopecht.team_season_rankings(season_id);

-- 3. Enable RLS
ALTER TABLE kopecht.team_season_rankings ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies
-- SELECT Policy - Users can view team rankings from their kicker
CREATE POLICY "access_control_on_team_season_rankings"
ON kopecht.team_season_rankings
AS PERMISSIVE
FOR SELECT
TO public
USING (
    EXISTS (
        SELECT 1
        FROM kopecht.teams t
        JOIN kopecht.player p ON p.kicker_id = t.kicker_id
        WHERE t.id = team_season_rankings.team_id 
          AND p.user_id = auth.uid()
    )
);

-- INSERT Policy
CREATE POLICY "insert_control_on_team_season_rankings"
ON kopecht.team_season_rankings
AS PERMISSIVE
FOR INSERT
TO public
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM kopecht.teams t
        JOIN kopecht.player p ON p.kicker_id = t.kicker_id
        WHERE t.id = team_season_rankings.team_id 
          AND p.user_id = auth.uid()
    )
);

-- UPDATE Policy
CREATE POLICY "update_control_on_team_season_rankings"
ON kopecht.team_season_rankings
AS PERMISSIVE
FOR UPDATE
TO public
USING (
    EXISTS (
        SELECT 1
        FROM kopecht.teams t
        JOIN kopecht.player p ON p.kicker_id = t.kicker_id
        WHERE t.id = team_season_rankings.team_id 
          AND p.user_id = auth.uid()
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM kopecht.teams t
        JOIN kopecht.player p ON p.kicker_id = t.kicker_id
        WHERE t.id = team_season_rankings.team_id 
          AND p.user_id = auth.uid()
    )
);

-- DELETE Policy
CREATE POLICY "delete_control_on_team_season_rankings"
ON kopecht.team_season_rankings
AS PERMISSIVE
FOR DELETE
TO public
USING (
    EXISTS (
        SELECT 1
        FROM kopecht.teams t
        JOIN kopecht.player p ON p.kicker_id = t.kicker_id
        WHERE t.id = team_season_rankings.team_id 
          AND p.user_id = auth.uid()
    )
);

-- 5. Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON kopecht.team_season_rankings TO authenticated;
GRANT USAGE ON SEQUENCE kopecht.team_season_rankings_id_seq TO authenticated;

-- 6. Function to get or create team season ranking
CREATE OR REPLACE FUNCTION kopecht.get_or_create_team_season_ranking(
    p_team_id BIGINT,
    p_season_id BIGINT
)
RETURNS kopecht.team_season_rankings
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_ranking kopecht.team_season_rankings;
BEGIN
    -- Try to get existing ranking
    SELECT * INTO v_ranking
    FROM kopecht.team_season_rankings
    WHERE team_id = p_team_id AND season_id = p_season_id;
    
    -- If not found, create it
    IF v_ranking IS NULL THEN
        INSERT INTO kopecht.team_season_rankings (team_id, season_id, wins, losses, mmr)
        VALUES (p_team_id, p_season_id, 0, 0, 1000)
        RETURNING * INTO v_ranking;
    END IF;
    
    RETURN v_ranking;
END;
$$;

-- 7. Function to update team season ranking after match
CREATE OR REPLACE FUNCTION kopecht.update_team_season_ranking(
    p_team_id BIGINT,
    p_season_id BIGINT,
    p_mmr_change INTEGER,
    p_won BOOLEAN
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    -- Ensure ranking exists
    PERFORM kopecht.get_or_create_team_season_ranking(p_team_id, p_season_id);
    
    -- Update the ranking
    UPDATE kopecht.team_season_rankings
    SET 
        mmr = mmr + p_mmr_change,
        wins = CASE WHEN p_won THEN wins + 1 ELSE wins END,
        losses = CASE WHEN NOT p_won THEN losses + 1 ELSE losses END
    WHERE team_id = p_team_id AND season_id = p_season_id;
END;
$$;

-- 8. Function to get team season rankings for a kicker/season (for leaderboard)
CREATE OR REPLACE FUNCTION kopecht.get_team_season_rankings(
    p_kicker_id BIGINT,
    p_season_id BIGINT
)
RETURNS TABLE (
    team_id BIGINT,
    team_name VARCHAR(50),
    logo_url TEXT,
    player1_id BIGINT,
    player1_name TEXT,
    player1_avatar TEXT,
    player2_id BIGINT,
    player2_name TEXT,
    player2_avatar TEXT,
    wins BIGINT,
    losses BIGINT,
    mmr BIGINT,
    total_matches BIGINT,
    win_rate NUMERIC
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        t.id AS team_id,
        t.name AS team_name,
        t.logo_url,
        p1.id AS player1_id,
        p1.name::TEXT AS player1_name,
        p1.avatar AS player1_avatar,
        p2.id AS player2_id,
        p2.name::TEXT AS player2_name,
        p2.avatar AS player2_avatar,
        COALESCE(tsr.wins, 0::BIGINT) AS wins,
        COALESCE(tsr.losses, 0::BIGINT) AS losses,
        COALESCE(tsr.mmr, 1000::BIGINT) AS mmr,
        COALESCE(tsr.wins, 0) + COALESCE(tsr.losses, 0) AS total_matches,
        CASE 
            WHEN COALESCE(tsr.wins, 0) + COALESCE(tsr.losses, 0) = 0 THEN 0
            ELSE ROUND(COALESCE(tsr.wins, 0)::NUMERIC / (COALESCE(tsr.wins, 0) + COALESCE(tsr.losses, 0)) * 100, 1)
        END AS win_rate
    FROM kopecht.teams t
    JOIN kopecht.player p1 ON t.player1_id = p1.id
    JOIN kopecht.player p2 ON t.player2_id = p2.id
    LEFT JOIN kopecht.team_season_rankings tsr ON t.id = tsr.team_id AND tsr.season_id = p_season_id
    WHERE t.kicker_id = p_kicker_id
      AND t.status = 'active'
    ORDER BY COALESCE(tsr.mmr, 1000) DESC, COALESCE(tsr.wins, 0) DESC;
END;
$$;

-- 9. Grant execute permissions
GRANT EXECUTE ON FUNCTION kopecht.get_or_create_team_season_ranking(BIGINT, BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION kopecht.update_team_season_ranking(BIGINT, BIGINT, INTEGER, BOOLEAN) TO authenticated;
GRANT EXECUTE ON FUNCTION kopecht.get_team_season_rankings(BIGINT, BIGINT) TO authenticated;
